### PR TITLE
port SNI from https://github.com/ztefn/haguichi (gtk4)

### PR DESCRIPTION
**Pull request by janesser**
if one day you'd like to be dropping gtk3 in favor of gtk4

### CODE REVIEW

**Comment by its-darsh** [comment]
Sorry about the - rather very long - delay, github sucks when comes to notifications.

I might be in need for more context about what actually does this PR provide.

**Comment by janesser** [comment]
@its-darsh by now gray relies on gtk3 dependency - the attached one was worked on when bitseater meteo upgraded to gtk4 - actually the code attached in this PR was in no lib yet, so would fit in libgray.

did you have plans of how long to stick to gtk3 ?

**Comment by its-darsh** [comment]
I don't have any plans sticking with a specific library.

We're trying to provide an universal library that would work everywhere, The issue is that Gtk3 is known and begin used more than Gtk4 especially when comes to the field of "docks and status bars"

I have no issues at all providing support for Gtk4 but at what cost?, dropping Gtk3 doesn't seem to be the best idea since most Gray users are going to be using it with Gtk3.

The reason behind sticking with Gtk3 is that one of Gray's dependencies (`libdbusmenu-gtk3`) depends on Gtk3, `libdbusmenu-gtk3` provides a menu over the DBus protocol (`StatusNotifierItem`)

So if we can implement an universal solution — perhaps a headless model with time-saving methods for developers using different toolkits. by doing so, we could eventually end up ditching `libdbusmenu-gtk3` in favor to our own implementation of a menu.

**Comment by janesser** [comment]
@its-darsh totally fine with me. 
once you feel the dependents are abandoning gtk3, this will be a possible direction of thinking. 

the libdbusmenu-gtk3 capability is contained in here.

for now, i shall close the PR. Ping me once that kind of thought will be resumed.

**Pull request closed without merging**
